import { house1, house2, house3, house4, house5, house6, house7, house8, house9, house10, house11 } from "../assets/images";

export const NavLinks = [
  { href: "/", label: "Home" },
  { href: "#location", label: "Locations" },
  { href: "/contact", label: "Contact Us" },
  { href: "/about", label: "About Us" },
];

export const slides = [
  {
    id: "slide1",
    src: house1,
  },
  {
    id: "slide2",
    src: house2,
  },
  {
    id: "slide3",
    src: house3,
  },
  {
    id: "slide4",
    src: house4,
  },
  {
    id: "slide5",
    src: house5,
  },
  {
    id: "slide6",
    src: house8,
  },
];

export const cardData = [
  {
    id: 1,
    imgURL: house1,
    label: "house1",
    loc: "Downtown Brampton",
    beds: 4,
    bath: 2,
    price: "0.02 ETH",
    area: "1500sq ",
    desc: "Brampton City Hall 2 Wellington St W Brampton, ON L6Y 1H3",
  },
  {
    id: 2,
    imgURL: house2,
    label: "house2",
    loc: "Gage Park St",
    beds: 4.5,
    bath: 2,
    price: "0.025 ETH",
    area: "1300sq ",
    desc: "49th Street to the north, 59th Street to the south, Central Park Avenue to the west",
  },
  {
    id: 3,
    imgURL: house3,
    label: "house3",
    loc: "Bramalea",
    beds: 3,
    bath: 1.5,
    price: "0.075 ETH",
    area: "1200sq ",
    desc: "30 Peel Centre Drive, Brampton, ON",
  },
  {
    id: 4,
    imgURL: house4,
    label: "house4",
    loc: "Brampton East St",
    beds: 2,
    bath: 2,
    price: "0.049 ETH",
    area: "1500sqft ",
    desc: " 9105 Airport Road, Brampton, ON L6S 0B8",
  },
  {
    id: 5,
    imgURL: house5,
    label: "house5",
    loc: "Heart Lake St",
    beds: 4,
    bath: 3,
    price: "0.050 ETH",
    area: "1500sq ",
    desc: "Range Rd 41, Turner Valley, Alberta T0L 2A0, CA",
  },
];

export const cardData2 = [
  {
    id: 1,
    imgURL: house6,
    label: "house6",
    loc: "Old City of Toronto",
    beds: 3,
    bath: 1,
    price: "0.09 ETH",
    area: "1500sq ",
    desc: "60 Queen Street West, Toronto, ON M5H 2S6",
  },
  {
    id: 2,
    imgURL: house7,
    label: "house7",
    loc: "York and East York",
    beds: 4,
    bath: 2,
    price: "0.075 ETH",
    area: "1300sq ",
    desc: " 157 King Street East, Toronto, ON M5C 1G6",
  },
  {
    id: 3,
    imgURL: house8,
    label: "house8",
    loc: "Scarborough",
    beds: 3,
    bath: 2,
    price: "0.085 ETH",
    area: "1200sq ",
    desc: "95 Front Street East, Toronto, ON M5A 1C3",
  },
  {
    id: 4,
    imgURL: house9,
    label: "house9",
    loc: "Richmond Hill",
    beds: 2,
    bath: 2,
    price: "0.045 ETH",
    area: "1500sqft ",
    desc: "55 Mill Street, Toronto, ON M5A 3C4",
  },
  {
    id: 5,
    imgURL: house10,
    label: "house10",
    loc: "Markham",
    beds: 2,
    bath: 2,
    price: "0.06 ETH",
    area: "1500sqft ",
    desc: "3456 Yonge Street, Toronto, ON M4N 3P1",
  },
  {
    id: 6,
    imgURL: house11,
    label: "house11",
    loc: "North York",
    beds: 2,
    bath: 2,
    price: "0.07 ETH",
    area: "1500sqft ",
    desc: "3456 Danforth Avenue, Toronto, ON M4C 1M1",
  },
  
];